intVariable = int(input("Enter number:"))
floatVariable = float(intVariable)
boolVariable = bool(intVariable)
stringVariable = str(intVariable)
print(f"int-{intVariable}\nfloat-{floatVariable}\nboolean-{boolVariable}\nstring-{stringVariable}")